# Generated by Django 5.1.7 on 2025-05-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todolist',
            new_name='title',
        ),
    ]
